version: '3.8'

services:
  clinicalx_main:
    image: lorkorblaq/clinicalx_main:48
    ports:
      - "8080:8080"
    networks:
      - clinicalx_network

  clinicalx_api:
    image: lorkorblaq/clinicalx_api:111
    ports:
      - "3000:3000"
    networks:
      - clinicalx_network

  clinicalx_nginx:
    image: lorkorblaq/clinicalx_nginx:latest
    depends_on:
      - clinicalx_main
      - clinicalx_api
    ports:
      - "80:80"
      - "443:443"
    networks:
      - clinicalx_network

networks:
  clinicalx_network:
    driver: bridge
